- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
   - name: Get New Session Rate
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_resource_usage
     register: setuprate
       
   - name: Get Fortiguard Status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: license_status
     register: fortiguard
         
   - name: Retrieve system global settings
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: network_arp
     register: arp_result

   - name: Get System status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_status
     register: status
     
   - name: Test get uptime
     fortinet.fortios.fortios_json_generic:
       vdom: "{{ vdom }}"
       json_generic:
         method: "GET"
         path: "/api/v2/monitor/web-ui/state"
     register: perf
      
   - name: Get CPU and Memory Usage
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_vdom-resource
     register: cpumem
     
   - name: Get Current Session Usage
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_global-resources
     register: session   
      
   - name: Get Policy Usage
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: firewall_policy
     register: policy    
     
   - name: Get FortiManager Status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_fortimanager_status
     register: fmg

   - name: Get FortiAnalyzer Status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: log_fortianalyzer
     register: faz

   - name: Get interface status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_available-interfaces
     register: interface
   
   - name: Get Test
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_interface
     register: test

   - name : Debug Interface
     debug:
       msg: "{{test}}"
    
   - name: Get NTP status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_ntp_status
     register: ntp

   - name: Get Route Statistics
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: router_statistics
     register: routestat
     
   - name: Get Route OSPF Neighbors
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: router_ospf_neighbors
     register: ospf_neighbors
     
   - name: Get Route BGP Neighbors
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: router_bgp_neighbors
     register: bgp_neighbors

   - name: Get IPsec tunnel status
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: vpn_ipsec
     register: ipsec_tunnel_status

   - name: Get configuration backup
     fortinet.fortios.fortios_monitor_fact:
       vdom: "{{ vdom }}"
       selector: system_config_backup
       params:
          scope: "global"
     register: backup_config
     
   - name: Render JSON using Jinja2 template
     template:
       src: fortigate.json.j2
       dest: "/home/chai/Desktop/ansible/fortigate/report/json/{{ inventory_hostname }}_PM.json"

   - name: Generate Report PM
     template:
       src: fortigate.j2
       dest: "/home/chai/Desktop/ansible/fortigate/report/text/{{ inventory_hostname }}-report.txt"
       
   - name: Save Backup Config
     copy:
       content: '{{ backup_config.meta.raw }}'
       dest: "/home/chai/Desktop/ansible/fortigate/backup/{{ inventory_hostname }}-config.cfg"
       
   - name: Run Python script
     ansible.builtin.command: python3 /home/chai/Desktop/ansible/fortigate/process.py {{ inventory_hostname }}
     register: result
     run_once: true
     
   - name: show output python
     run_once: true
     debug:
       msg: "{{result.stdout}}"
