### FortiGate Host###
[fortigates]
CTC	ansible_host=1.1.1.1
LPR	ansible_host=1.1.1.1
BPL ansible_host=1.1.1.1
[CENTRAL]
SNO  ansible_host=2.2.2.2

### FortiGate OS Modules ###
[all:vars]
ansible_user = test
ansible_password = test
ansible_network_os = fortinet.fortios.fortios

